<?php
$routes = [
    '' => 'index.php',
    'contacts' => 'contacts.php',
    'garant' => 'garant.php',
    'aut-reg' => 'aut-reg.php',
    'reg' => 'reg.php',
    'aut' => 'aut.php',
    'setings' => 'setings.php',
    'catalog' => 'catalog.php',
    'admin' => 'admin.php',
    'tovar' => 'tovar.php',
    'add-tovars' => 'add-tovars.php',
    'info-tovars' => 'info-tovars.php',
    'add-cars' => 'add-cars.php',
    'cars' => 'cars.php',
    'update_cars' => 'update_cars.php',
    'del_cars' => 'del_cars.php',
    'order' => 'order.php',
    'shoping' => 'shoping.php',
    'receiving' => 'receiving.php',
    'order-result' => 'order-result.php',
    'shop' => 'shop.php',
    'otmena' => 'otmena.php',
    'update' => 'update.php',
    'update_tovar' => 'update_tovar.php',
    'del' => 'del.php',

];